#!/usr/bin/osascript

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title newTerm
# @raycast.mode compact

# Optional parameters:
# @raycast.icon 🤖

# Documentation:
# @raycast.description open new terminal
# @raycast.author shezcode
# @raycast.authorURL https://raycast.com/shezcode

tell application "iTerm"
  set newWindow to (create window with default profile)
  tell current session of newWindow
    write text "cd ~/; clear; pwd"
  end tell
end tell

tell application "System Events" to tell process "Raycast" to keystroke "w" using command down
